package com.foodfinder.csv;

public enum CsvErrorCode {
    UNKNOWN_HEADER,
    MISSING_REQUIRED,
    INVALID_SLUG,
    INVALID_STATUS,
    INVALID_TYPE,
    INVALID_NUMBER,
    INVALID_BOOLEAN,
    INVALID_DATE,
    INVALID_URL,
    INVALID_CURRENCY,
    INVALID_LATITUDE,
    INVALID_LONGITUDE,
    INVALID_GEO_PAIR,
    INVALID_VALUE,
    UNKNOWN_RESTAURANT,
    UNKNOWN_MENU,
    UNKNOWN_PRODUCT,
    UNKNOWN_KEY_IN_SAME_FILE,
    DUPLICATE_KEY_IN_FILE,
    VALIDITY_RANGE,
    PRICE_NEGATIVE,
    SORT_ORDER_NEGATIVE,
    STORAGE_BOTH_OR_NEITHER,
    SHA256_FORMAT,
    PRIMARY_DEMOTED
}
