package com.foodfinder.csv;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * End-to-end test: import the real legacy CSV files generated by
 * {@code data/legacy-import/generate.py} and verify the resulting counts.
 *
 * <p>Skipped silently if the CSV files are not present (e.g. CI without
 * the legacy-export step).</p>
 */
@SpringBootTest
@Transactional
class LegacyImportTest {

    @Autowired RestaurantCsv restaurantCsv;
    @Autowired MenuCsv menuCsv;
    @Autowired ProductCsv productCsv;
    @Autowired MenuItemCsv menuItemCsv;
    @Autowired PhotoCsv photoCsv;

    @Test
    void importLegacyCsvs() throws Exception {
        var dir = Paths.get("data/legacy-import");
        if (!Files.isDirectory(dir)) {
            // legacy CSVs not present in this environment; skip
            return;
        }
        // order matters: restaurants → menus → products → menu_items → photos
        var report1 = restaurantCsv.parse(new StringReader(Files.readString(dir.resolve("restaurants.csv"))), false);
        assertThat(report1.errors()).isEmpty();
        assertThat(report1.inserted()).isGreaterThan(0);

        var report2 = menuCsv.parse(new StringReader(Files.readString(dir.resolve("menus.csv"))), false);
        assertThat(report2.errors()).isEmpty();
        assertThat(report2.inserted()).isGreaterThan(0);

        var report3 = productCsv.parse(new StringReader(Files.readString(dir.resolve("products.csv"))), false);
        assertThat(report3.errors()).isEmpty();
        assertThat(report3.inserted()).isGreaterThan(0);

        var report4 = menuItemCsv.parse(new StringReader(Files.readString(dir.resolve("menu_items.csv"))), false);
        assertThat(report4.errors()).isEmpty();
        assertThat(report4.inserted()).isGreaterThan(0);

        var report5 = photoCsv.parse(new StringReader(Files.readString(dir.resolve("photos.csv"))), false);
        assertThat(report5.errors()).isEmpty();
        assertThat(report5.inserted()).isGreaterThan(0);
    }
}
