-- V1__catalog.sql
-- FoodFinder catalog schema. Flyway is the only schema authority.
-- Design decisions:
--   * internal BIGINT identity PKs, stable lowercase slug keys for API/CSV
--   * VARCHAR + CHECK for all statuses (no PostgreSQL enum types)
--   * same-restaurant invariant enforced with composite foreign keys
--   * price/section/availability live on menu_item, never on product

CREATE TABLE restaurant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_key  VARCHAR(120) NOT NULL,
    name            VARCHAR(200) NOT NULL,
    website_url     TEXT,
    address_line    TEXT,
    city            VARCHAR(120) NOT NULL DEFAULT 'Cluj-Napoca',
    latitude        NUMERIC(9,6),
    longitude       NUMERIC(9,6),
    status          VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_restaurant_key UNIQUE (restaurant_key),
    CONSTRAINT ck_restaurant_key_slug
        CHECK (restaurant_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_restaurant_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_restaurant_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_restaurant_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_restaurant_geo_pair
        CHECK ((latitude IS NULL) = (longitude IS NULL))
);

CREATE INDEX ix_restaurant_status ON restaurant (status);

CREATE TABLE menu (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_key        VARCHAR(120) NOT NULL,
    restaurant_id   BIGINT NOT NULL REFERENCES restaurant (id),
    name            VARCHAR(200) NOT NULL,
    menu_type       VARCHAR(20) NOT NULL DEFAULT 'PERMANENT',
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    source_url      TEXT,
    valid_from      DATE,
    valid_to        DATE,
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_menu_key UNIQUE (menu_key),
    -- supports composite FKs from menu_item (same-restaurant invariant)
    CONSTRAINT uq_menu_restaurant_id UNIQUE (restaurant_id, id),
    CONSTRAINT ck_menu_key_slug
        CHECK (menu_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_menu_type
        CHECK (menu_type IN ('PERMANENT', 'DAILY', 'WEEKLY', 'SEASONAL', 'OTHER')),
    CONSTRAINT ck_menu_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT ck_menu_validity
        CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX ix_menu_restaurant_status ON menu (restaurant_id, status);

CREATE TABLE product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_key     VARCHAR(160) NOT NULL,
    restaurant_id   BIGINT NOT NULL REFERENCES restaurant (id),
    name            VARCHAR(250) NOT NULL,
    description     TEXT,
    weight_text     VARCHAR(100),
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_product_key UNIQUE (product_key),
    -- supports composite FKs from menu_item / photo (same-restaurant invariant)
    CONSTRAINT uq_product_restaurant_id UNIQUE (restaurant_id, id),
    CONSTRAINT ck_product_key_slug
        CHECK (product_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_product_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE INDEX ix_product_restaurant_status ON product (restaurant_id, status);
CREATE INDEX ix_product_name ON product (name);

CREATE TABLE menu_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id         BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    restaurant_id   BIGINT NOT NULL,
    section_name    VARCHAR(200) NOT NULL DEFAULT 'Altele',
    price           NUMERIC(12,2),
    currency        VARCHAR(3) NOT NULL DEFAULT 'RON',
    available       BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_menu_item UNIQUE (menu_id, product_id),
    -- composite FKs make cross-restaurant links impossible at the DB level
    CONSTRAINT fk_menu_item_menu
        FOREIGN KEY (restaurant_id, menu_id) REFERENCES menu (restaurant_id, id),
    CONSTRAINT fk_menu_item_product
        FOREIGN KEY (restaurant_id, product_id) REFERENCES product (restaurant_id, id),
    CONSTRAINT ck_menu_item_price
        CHECK (price IS NULL OR price >= 0),
    CONSTRAINT ck_menu_item_sort_order
        CHECK (sort_order >= 0),
    CONSTRAINT ck_menu_item_currency
        CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX ix_menu_item_menu_section_sort
    ON menu_item (menu_id, section_name, sort_order);
CREATE INDEX ix_menu_item_product ON menu_item (product_id);

CREATE TABLE photo (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_key               VARCHAR(160) NOT NULL,
    restaurant_id           BIGINT NOT NULL REFERENCES restaurant (id),
    product_id              BIGINT,
    source_type             VARCHAR(30) NOT NULL,
    storage_key             TEXT,
    external_url            TEXT,
    thumbnail_storage_key   TEXT,
    mime_type               VARCHAR(100),
    width                   INTEGER,
    height                  INTEGER,
    alt_text                VARCHAR(300),
    is_primary              BOOLEAN NOT NULL DEFAULT FALSE,
    status                  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    sha256                  VARCHAR(64),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_photo_key UNIQUE (photo_key),
    CONSTRAINT ck_photo_key_slug
        CHECK (photo_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_photo_source_type
        CHECK (source_type IN ('UPLOAD', 'RESTAURANT_OFFICIAL', 'GOOGLE_PROTOTYPE', 'IMPORTED_URL')),
    CONSTRAINT ck_photo_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    -- exactly one of storage_key / external_url must be populated
    CONSTRAINT ck_photo_storage_xor
        CHECK ((storage_key IS NULL) <> (external_url IS NULL)),
    CONSTRAINT ck_photo_width
        CHECK (width IS NULL OR width > 0),
    CONSTRAINT ck_photo_height
        CHECK (height IS NULL OR height > 0),
    -- when a product is linked it must belong to the same restaurant;
    -- a NULL product_id makes the composite FK trivially satisfied
    CONSTRAINT fk_photo_product
        FOREIGN KEY (restaurant_id, product_id) REFERENCES product (restaurant_id, id)
);

-- at most one primary photo per product
CREATE UNIQUE INDEX ux_photo_primary_per_product
    ON photo (product_id)
    WHERE is_primary AND product_id IS NOT NULL;

-- at most one restaurant-level primary photo (no product)
CREATE UNIQUE INDEX ux_photo_primary_per_restaurant
    ON photo (restaurant_id)
    WHERE is_primary AND product_id IS NULL;

CREATE INDEX ix_photo_restaurant_product_status
    ON photo (restaurant_id, product_id, status);

CREATE TABLE menu_asset (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_key           VARCHAR(160) NOT NULL,
    menu_id             BIGINT NOT NULL REFERENCES menu (id),
    asset_type          VARCHAR(20) NOT NULL,
    original_filename   VARCHAR(255),
    storage_key         TEXT,
    source_url          TEXT,
    mime_type           VARCHAR(100),
    size_bytes          BIGINT,
    sha256              VARCHAR(64),
    sort_order          INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_menu_asset_key UNIQUE (asset_key),
    CONSTRAINT ck_menu_asset_key_slug
        CHECK (asset_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_menu_asset_type
        CHECK (asset_type IN ('PDF', 'IMAGE', 'URL')),
    -- exactly one of storage_key / source_url must be populated
    CONSTRAINT ck_menu_asset_storage_xor
        CHECK ((storage_key IS NULL) <> (source_url IS NULL)),
    CONSTRAINT ck_menu_asset_size
        CHECK (size_bytes IS NULL OR size_bytes > 0),
    CONSTRAINT ck_menu_asset_sort_order
        CHECK (sort_order >= 0),
    CONSTRAINT ck_menu_asset_sha256
        CHECK (sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_menu_asset_menu_sort ON menu_asset (menu_id, sort_order);
