-- V2__csv_import_log.sql
-- Audit trail for every CSV import. One row per run, regardless of
-- dry-run / commit. Captures: who ran it, which resource, what file,
-- counts (total / inserted / updated / errored), and outcome.
--
-- This is a write-only table (no UPDATE). Runs that fail partway still
-- leave a row with status=FAILED so the admin can see who tried what.

CREATE TABLE csv_import_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(40) NOT NULL,
    filename        VARCHAR(255),
    actor           VARCHAR(120) NOT NULL,         -- principal name (admin)
    dry_run         BOOLEAN NOT NULL,
    total_rows      INT NOT NULL DEFAULT 0,
    inserted_rows   INT NOT NULL DEFAULT 0,
    updated_rows    INT NOT NULL DEFAULT 0,
    error_count     INT NOT NULL DEFAULT 0,
    status          VARCHAR(20) NOT NULL DEFAULT 'OK',
    failure_message TEXT,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_csv_import_log_slug
        CHECK (slug IN ('restaurants','menus','products','menu-items','photos','menu-assets','bundle')),
    CONSTRAINT ck_csv_import_log_status
        CHECK (status IN ('OK','FAILED')),
    CONSTRAINT ck_csv_import_log_finished_after_started
        CHECK (finished_at >= started_at)
);

CREATE INDEX ix_csv_import_log_started_at ON csv_import_log (started_at DESC);
CREATE INDEX ix_csv_import_log_slug ON csv_import_log (slug, started_at DESC);
